use res_regex::RegexParser;
#[test]
fn moz_central() {
    let _ = pretty_env_logger::try_init();
    for (i, regex) in REGEXES.iter().enumerate() {
        let mut parser = RegexParser::new(regex).expect("unable to contruct the parser");
        parser.parse().expect(&format!("{}: failed to parse {:?}", i, regex));
    }
}
static REGEXES: &[&str] = &[
     r#"/agggtaaa|tttaccct/ig"#,
    r#"/[cgt]gggtaaa|tttaccc[acg]/ig"#,
    r#"/a[act]ggtaaa|tttacc[agt]t/ig"#,
    r#"/ag[act]gtaaa|tttac[agt]ct/ig"#,
    r#"/agg[act]taaa|ttta[agt]cct/ig"#,
    r#"/aggg[acg]aaa|ttt[cgt]ccct/ig"#,
    r#"/agggt[cgt]aa|tt[acg]accct/ig"#,
    r#"/agggta[cgt]a|t[acg]taccct/ig"#,
    r#"/agggtaa[cgt]|[acg]ttaccct/ig"#,
    r#"/>.*\\n|\\n/g"#,
    r#"/^[\\],:{}\\s]*$/"#,
    r#"/\\\\./g"#,
    r#"/\"[^\"\\\\\\n\\r]*\"|true|false|null|-?\\d+(?:\\.\\d*)?(:?[eE][+\\-]?\\d+)?/g"#,
    // r#"/(?:^|:|,)(?:\\s*\\[)+/g"#,
    r#"/[\"\\\\\\x00-\\x1f]/"#,
    r#"/[\\x00-\\x1f\\\\\"]/g"#,
    r#"/([0-9.]+)px/g"#,
    r#"/[\\0\\t\\n\\v\\f\\r\\xa0\'\"!-]/g"#,
    r#"/!\\d\\d?\\d?!/g"#,
    r#"/[\\u0080-\\u07ff]/g"#,
    r#"/[\\u0800-\\uffff]/g"#,
    r#"/[\\u00c0-\\u00df][\\u0080-\\u00bf]/g"#,
    r#"/[\\u00e0-\\u00ef][\\u0080-\\u00bf][\\u0080-\\u00bf]/g"#,
    r#"/^.*? ([A-Z]{3}) [0-9]{4}.*$/"#,
    r#"/^.*?\\(([A-Z])[a-z]+ ([A-Z])[a-z]+ ([A-Z])[a-z]+\\)$/"#,
    r#"/(\'|\\\\)/g"#,
    r#"/^2017-09-05Tuesday, September 05, 2017 [0-9:]* AM$/"#,
    r#"/^/"#,
    r#"/can\'t convert the number/"#,
    r#"/attempting to convert an empty CDataFinalizer at argument 1 of ctypes\\.FunctionType\\(ctypes\\.default_abi, ctypes\\.int32_t, \\[ctypes\\.int32_t\\]\\)\\.ptr\\(ctypes\\.UInt64\\(\\\"[x0-9A-Fa-f]+\\\"\\)\\)/"#,
    r#"/can\'t pass the string \"foo\" to argument 1 of ctypes\\.FunctionType\\(ctypes\\.default_abi, ctypes\\.voidptr_t, \\[ctypes\\.int32_t\\]\\)\\.ptr\\(ctypes\\.UInt64\\(\"[x0-9A-Fa-f]+\"\\)\\)/"#,
    r#"/can\'t convert the string \\\"foo\\\" to the \'x\' field \\(int32_t\\) of test_struct at argument 1 of ctypes\\.FunctionType\\(ctypes\\.default_abi, ctypes.int32_t, \\[test_struct\\]\\)\\.ptr\\(ctypes\\.UInt64\\(\\\"[x0-9A-Fa-f]+\\\"\\)\\)/"#,
    r#"/property count of the object \\(\\{x:\\\"foo\\\", y:\\\"bar\\\"\\}\\) does not match to field count of the type test_struct \\(expected 1, got 2\\) at argument 1 of ctypes\\.FunctionType\\(ctypes\\.default_abi, ctypes\\.int32_t, \\[test_struct\\]\\)\\.ptr\\(ctypes\\.UInt64\\(\\\"[x0-9A-Fa-f]+\\\"\\)\\)/"#,
    r#"/property name the number 0 of the object \\(\\{0:\\\"foo\\\"\\}\\) is not a string at argument 1 of ctypes\\.FunctionType\\(ctypes\\.default_abi, ctypes\\.int32_t, \\[test_struct\\]\\)\\.ptr\\(ctypes\\.UInt64\\(\\\"[x0-9A-Fa-f]+\\\"\\)\\)/"#,
    r#"/base type ctypes\\.int32_t\\.ptr\\(ctypes\\.UInt64\\(\\\"[x0-9A-Fa-f]+\\\"\\)\\) is not an 8-bit or 16-bit integer or character type/"#,
    r#"/^1+0+$/"#,
    r#"/^1+$/"#,
    r#"/^1+0+1$/"#,
    r#"/I/"#,
    r#"/(.*)$/"#,
    r#"/./"#,
    r#"/x/"#,
    r#"/^\\w is not a function$/"#,
    r#"/^ba/"#,
    r#"/(((\\w+):\\/\\/)([^\\/:]*)(:(\\d+))?)?([^#?]*)(\\?([^#]*))?(#(.*))?/"#,
    r#"/^\\s*|\\s*$/g"#,
    r#"/\\bQBZPbageby_cynprubyqre\\b/"#,
    r#"/,/"#,
    r#"/\\bQBZPbageby_cynprubyqre\\b/g"#,
    r#"/^[\\s\\xa0]+|[\\s\\xa0]+$/g"#,
    r#"/(\\d*)(\\D*)/g"#,
    r#"/=/"#,
    r#"/(^|\\s)lhv\\-h(\\s|$)/"#,
    r#"/\\#/g"#,
    r#"/\\./g"#,
    r#"/\'/g"#,
    r#"/\\?[\\w\\W]*(sevraqvq|punaaryvq|tebhcvq)=([^\\&\\?#]*)/i"#,
    r#"/\\s+/g"#,
    r#"/^\\s*(\\S*(\\s+\\S+)*)\\s*$/"#,
    r#"/(-[a-z])/i"#,
    r#"/qqqq|qqq|qq|q|ZZZZ|ZZZ|ZZ|Z|llll|ll|l|uu|u|UU|U|zz|z|ff|f|gg|g|sss|ss|s|mmm|mm|m/g"#,
    r#"/JroXvg\\/(\\S+)/"#,
    r#"/\\[/g"#,
    r#"/(?:^|;)\\s*sevraqfgre_ynat=([^;]*)/"#,
    r#"/([a-zA-Z]|\\s)+/"#,
    r#"/(^|[^\\\\])\\\"\\\\\\/Qngr\\((-?[0-9]+)\\)\\\\\\/\\\"/g"#,
    r#"/^\\s+|\\s+$/g"#,
    r#"/(?:^|\\s+)ba(?:\\s+|$)/"#,
    r#"/[+, ]/"#,
    r#"/ybnqrq|pbzcyrgr/"#,
    r#"/(\\s)+e/"#,
    r#"/Fnsnev\\/(\\d+\\.\\d+)/"#,
    r#"/d1/g"#,
    r#"/NQ_VQ/g"#,
    r#"/d2/g"#,
    r#"/_/g"#,
    r#"/(?:ZFVR.(\\d+\\.\\d+))|(?:(?:Sversbk|TenaCnenqvfb|Vprjrnfry).(\\d+\\.\\d+))|(?:Bcren.(\\d+\\.\\d+))|(?:NccyrJroXvg.(\\d+(?:\\.\\d+)?))/"#,
    r#"/(Znp BF K)|(Jvaqbjf;)/"#,
    r#"/Trpxb\\/([0-9]+)/"#,
    r#"/\\bso_zrah\\b/"#,
    r#"/^(?:(?:[^:\\/?#]+):)?(?:\\/\\/(?:[^\\/?#]*))?([^?#]*)(?:\\?([^#]*))?(?:#(.*))?/"#,
    r#"/uggcf?:\\/\\/([^\\/]+\\.)?snprobbx\\.pbz\\//"#,
    r#"/\"/g"#,
    r#"/^([^?#]+)(?:\\?([^#]*))?(#.*)?/"#,
    r#"/\\buvqqra_ryrz\\b/g"#,
    r#"/\\buvqqra_ryrz\\b/"#,
    r#"/puebzr/i"#,
    r#"/(?:^|\\s+)gvzrfgnzc(?:\\s+|$)/"#,
    r#"/-\\D/g"#,
    r#"/\\bnpgvingr\\b/"#,
    r#"/%2R/gi"#,
    r#"/%2S/gi"#,
    r#"/^(mu-(PA|GJ)|wn|xb)$/"#,
    r#"/\\s?;\\s?/"#,
    r#"/%\\w?$/"#,
    r#"/TNQP=([^;]*)/i"#,
    r#"/[<>]/g"#,
    r#"/[A-Za-z]/g"#,
    r#"/zfvr/gi"#,
    r#"/bcren/gi"#,
    r#"/%3P/g"#,
    r#"/%3R/g"#,
    r#"/%3q/g"#,
    r#"/uers|fep|fryrpgrq/"#,
    r#"/\\s*([+>~\\s])\\s*([a-zA-Z#.*:\\[])/g"#,
    r#"/^(\\w+|\\*)$/"#,
    r#"/\\\\/g"#,
    r#"/ /g"#,
    r#"/\\/\\xc4\\/t/"#,
    r#"/\\W/g"#,
    r#"/uers|fep|fglyr/"#,
    r#"/\\*/g"#,
    r#"/\\bnpgvir\\b/"#,
    r#"/sversbk/i"#,
    r#"/zfvr/i"#,
    r#"/bcren/i"#,
    r#"/\\.([\\w-]+)|\\[(\\w+)(?:([!*^$~|]?=)[\"\']?(.*?)[\"\']?)?\\]|:([\\w-]+)(?:\\([\"\']?(.*?)?[\"\']?\\)|$)/g"#,
    r#"/(\\s+e|\\s+o[0-9]+)/"#,
    r#"/</g"#,
    r#"/>/g"#,
    r#"/(?:^|\\s+)fryrpgrq(?:\\s+|$)/"#,
    r#"/\\&/g"#,
    r#"/\\+/g"#,
    r#"/\\?/g"#,
    r#"/\\t/g"#,
    r#"/(\\$\\{nqiHey\\})|(\\$nqiHey\\b)/g"#,
    r#"/(\\$\\{cngu\\})|(\\$cngu\\b)/g"#,
    r#"/NccyrJroXvg\\/([^\\s]*)/"#,
    r#"/XUGZY/"#,
    r#"/(\\$\\{cebg\\})|(\\$cebg\\b)/g"#,
    r#"/^(.*)\\..*$/"#,
    r#"/^.*e(.*)$/"#,
    r#"/^.*\\s+(\\S+\\s+\\S+$)/"#,
    r#"/(\\$\\{ubfg\\})|(\\$ubfg\\b)/g"#,
    r#"/(\\$\\{dz\\})|(\\$dz\\b)/g"#,
    r#"/e/"#,
    r#"/##yv4##/gi"#,
    r#"/##yv16##/gi"#,
    r#"/##yv19##/gi"#,
    r#"/(?:^|\\s+)bss(?:\\s+|$)/"#,
    r#"/^(([^:\\/?#]+):)?(\\/\\/([^\\/?#]*))?([^?#]*)(\\?([^#]*))?(#(.*))?$/"#,
    r#"/^[^<]*(<(.|\\s)+>)[^>]*$|^#(\\w+)$/"#,
    r#"/##yv0##/gi"#,
    r#"/##\\/o##/gi"#,
    r#"/#~#argjbexybtb#~#/g"#,
    r#"/ Zbovyr\\//"#,
    r#"/##yv1##/gi"#,
    r#"/AbxvnA[^\\/]*/"#,
    r#"/(?:^|\\s+)bss(?:\\s+|$)/g"#,
    r#"/(\\$\\{0\\})|(\\$0\\b)/g"#,
    r#"/(\\$\\{1\\})|(\\$1\\b)/g"#,
    r#"/(\\$\\{pbzcyrgr\\})|(\\$pbzcyrgr\\b)/g"#,
    r#"/(\\$\\{sentzrag\\})|(\\$sentzrag\\b)/g"#,
    r#"/(\\$\\{ubfgcbeg\\})|(\\$ubfgcbeg\\b)/g"#,
    r#"/(\\$\\{cebgbpby\\})|(\\$cebgbpby\\b)/g"#,
    r#"/(\\$\\{dhrel\\})|(\\$dhrel\\b)/g"#,
    r#"/(\\$\\{2\\})|(\\$2\\b)/g"#,
    r#"/(\\$\\{3\\})|(\\$3\\b)/g"#,
    r#"/ PC=i=(\\d+)&oe=(.)/"#,
    r#"/Fnsnev|Xbadhrebe|XUGZY/gi"#,
    r#"/\\{0\\}/g"#,
    r#"/(^|.)(ronl|qri-ehf3.wbg)(|fgberf|zbgbef|yvirnhpgvbaf|jvxv|rkcerff|punggre).(pbz(|.nh|.pa|.ux|.zl|.ft|.oe|.zk)|pb(.hx|.xe|.am)|pn|qr|se|vg|ay|or|ng|pu|vr|va|rf|cy|cu|fr)$/i"#,
    r#"/\\b[a-z]/g"#,
    r#"/^uggc:\\/\\//"#,
    r#"/(?:^|\\s+)qvfnoyrq(?:\\s+|$)/"#,
    r#"/\\d+/g"#,
    r#"/[A-Z]/g"#,
    r#"/#([\\w-]+)/"#,
    r#"/NqborNVE\\/([^\\s]*)/"#,
    r#"/NccyrJroXvg\\/([^ ]*)/"#,
    r#"/XUGZY/gi"#,
    r#"/^(?:obql|ugzy)$/i"#,
    r#"/^(\\w+|\\*)/"#,
    r#"/znp|jva|yvahk/i"#,
    r#"/eton?\\([\\d\\s,]+\\)/"#,
    r#"/\\r/g"#,
    r#"/((ZFVR\\s+([6-9]|\\d\\d)\\.))/"#,
    r#"/Xbadhrebe|Fnsnev|XUGZY/"#,
    r#"/zrah_byq/g"#,
    r#"/^([#.]?)((?:[\\w\\u0128-\\uffff*_-]|\\\\.)*)/"#,
    r#"/\\{1\\}/g"#,
    r#"/\\s+/"#,
    r#"/(\\$\\{4\\})|(\\$4\\b)/g"#,
    r#"/(\\$\\{5\\})|(\\$5\\b)/g"#,
    r#"/\\{2\\}/g"#,
    r#"/[^+>] [^+>]/"#,
    r#"/\\bucpyv\\s*=\\s*([^;]*)/i"#,
    r#"/^((?:[\\w\\u0128-\\uffff*_-]|\\\\.)+)(#)((?:[\\w\\u0128-\\uffff*_-]|\\\\.)+)/"#,
    r#"/^([>+~])\\s*(\\w*)/i"#,
    r#"/^>\\s*((?:[\\w\\u0128-\\uffff*_-]|\\\\.)+)/"#,
    r#"/^[\\s[]?shapgvba/"#,
    r#"/v\\/g.tvs#(.*)/i"#,
    r#"/&/g"#,
    r#"/(\\$\\{anzr\\})|(\\$anzr\\b)/g"#,
    r#"/(..-HF)(\\|(\\d+)|)/i"#,
    r#"/ZFVR\\s+5[.]01/"#,
    r#"/HF(?=;)/i"#,
    r#"/\\bp:(..)/i"#,
    r#"/\\bhfucce\\s*=\\s*([^;]*)/i"#,
    r#"/\\bjci\\s*=\\s*([^;]*)/i"#,
    r#"/\\|p:([a-z]{2})/i"#,
    r#"/^Fubpxjnir Synfu (\\d)/"#,
    r#"/jroxvg/"#,
    r#"/eaq_zbqobkva/"#,
    r#"/^erzbgr_vsenzr_/"#,
    r#"/\\-/g"#,
    r#"/^$/"#,
    r#"/^znk\\d+$/"#,
    r#"/^zva\\d+$/"#,
    r#"/^erfgber$/"#,
    r#"/frpgvba\\d+_pbagragf/"#,
    r#"/;\\s*/"#,
    r#"/(\\$\\{inyhr\\})|(\\$inyhr\\b)/g"#,
    r#"/(\\$\\{abj\\})|(\\$abj\\b)/g"#,
    r#"/\\s+$/"#,
    r#"/^\\s+/"#,
    r#"/(\\\\\\\"|\\x00-|\\x1f|\\x7f-|\\x9f|\\u00ad|\\u0600-|\\u0604|\\u070f|\\u17b4|\\u17b5|\\u200c-|\\u200f|\\u2028-|\\u202f|\\u2060-|\\u206f|\\ufeff|\\ufff0-|\\uffff)/g"#,
    r#"/^(:)([\\w-]+)\\(\"?\'?(.*?(\\(.*?\\))?[^(]*?)\"?\'?\\)/"#,
    r#"/^([:.#]*)((?:[\\w\\u0128-\\uffff*_-]|\\\\.)+)/"#,
    r#"/^(\\[) *@?([\\w-]+) *([!*$^~=]*) *(\'?\"?)(.*?)\\4 *\\]/"#,
    r#"/^.*\\.(.*)\\s.*$/"#,
    r#"/^.*jroxvg\\/(\\d+(\\.\\d+)?).*$/"#,
    r#"/\\b\\w+\\b/g"#,
    r#"/\\//g"#,
    r#"/#[a-z0-9]+$/i"#,
    r#"/(?:^|\\s+)lhv-ani(?:\\s+|$)/"#,
    r#"/(?:^|\\s+)lhv-anifrg(?:\\s+|$)/"#,
    r#"/(?:^|\\s+)lhv-anifrg-gbc(?:\\s+|$)/"#,
    r#"/(pbzcngvoyr|jroxvg)/"#,
    r#"/.+(?:ei|vg|en|vr)[\\/: ]([\\d.]+)/"#,
    r#"/\\/onfr.wf(\\?.+)?$/"#,
    r#"/xbadhrebe/"#,
    r#"/znp/"#,
    r#"/zbmvyyn/"#,
    r#"/zfvr/"#,
    r#"/ag\\s5\\.1/"#,
    r#"/bcren/"#,
    r#"/fnsnev/"#,
    r#"/jva/"#,
    r#"/jvaqbjf/"#,
    r#"/^[a-z\\s]*/i"#,
    r#"/tracejit/"#,
    r#"/a/"#,
    r#"/s/"#,
    r#"/@/"#,
    r#"/abc/"#,
    r#"/jsreftest.html/"#,
    r#"/\\\\n/g"#,
    r#"/[^\\x20-\\x7E]+/g"#,
    r#"/\\s/"#,
    r#"/abcdef/g"#,
    r#"/a\\.*b[cC]+/g"#,
    r#"/bar\\d\\d/"#,
    r#"/bar\\d\\d/g"#,
    r#"/bar(\\d\\d)/g"#,
    r#"/abcd[eE]/g"#,
    r#"/b[aA]r/"#,
    r#"/abcdefghijklm[0-5]/"#,
    r#"/bar\\u0178\\d/i"#,
    r#"/invalid conversion to integer/"#,
    r#"/^function\\s*[a-zA-Z$_0-9]*\\s*\\(([^)]*)\\)\\s*{\\s*([^*]*?)[\\s;]*(?:return\\s*(.*?)[;\\s]*)?}$/"#,
    r#"/__Z[\\w\\d_]+/g"#,
    r#"/\\.(jpg|jpeg|png|bmp)$/i"#,
    r#"/> WebAssembly.Module\":wasm-function\\[1\\]:0x/"#,
    r#"/\\(ref T\\) types not enabled|bad type/"#,
    r#"/bad [Tt]able grow delta/"#,
    r#"/import object field \'i32\' is not a Number/"#,
    r#"/import object field \'\\w*\' is not an Object/"#,
    r#"/Function label \'\\$b\' not found/"#,
    r#"/Local label \'\\$a\' not found/"#,
    r#"/Function label \'\\$abc\' not found/"#,
    r#"/Signature label \'\\$b\' not found/"#,
    r#"/Signature label \'\\$c\' not found/"#,
    r#"/branch target label \'\\$a\' not found/"#,
    r#"/^Symbol\\((.+)\\)$/"#,
    r#"/\\w+|[^\\s]/g"#,
    r#"/null/"#,
    r#"/0/"#,
    r#"/12.12/"#,
    r#"/0.1/"#,
    r#"/20000/"#,
    r#"/[\\u0076\\u0095]/gm"#,
    r#"/a/g"#,
    r#"/a/y"#,
    r#"/0./"#,
    r#"/\\\\u00fd[]/"#,
    r#"/d1/ig"#,
    r#"/%/g"#,
    r#"/foo(ba(r))?/"#,
    r#"/(\\d+)/"#,
    r#"/missing/"#,
    r#"/^[a-z0-9\\.]+$/gi"#,
    r#"/foo$/"#,
    r#"/(.*)foo$/"#,
    r#"/(str)\\d*0/y"#,
    r#"/[^]/g"#,
    r#"/((?=()+))?/"#,
    r#"/abc(WHOO!)?def/y"#,
    r#"/s(\\s|.)*?e/gi"#,
    r#"/incompatible/"#,
    r#"/(?:){1,60}/"#,
    r#"/(bar)?/"#,
    r#"/foo(bar)?bar/"#,
    r#"/(?!(?!(?!6)[\\Wc]))/i"#,
    r#"/^[\\w\\-]+:\\/+(?!\\/)(?:[^.\\/]+\\.)*?reports\\.adblockplus\\.org(?:[\\x00-\\x24\\x26-\\x2C\\x2F\\x3A-\\x40\\x5B-\\x5E\\x60\\x7B-\\x80]|$)/i"#,
    r#"/()()()\\3/"#,
    r#"/a(b)c/"#,
    r#"/(p)/"#,
    r#"/(^\\n*)/"#,
    r#"/a(\\w+)c/"#,
    r#"/1(\\d+)3/"#,
    r#"/(?:|a)*/"#,
    r#"/^@<string>:1:1\\n/"#,
    r#"/^@candelabra:6502:1\\n/"#,
    r#"/\\/\\*DUPTRY\\d+\\*\\//"#,
    r#"/(two|2)\\s*problems/"#,
    r#"/.*(a\\w).*/i"#,
    r#"/hi/g"#,
    r#"/(?:(?=g))|(?:m).{2147483648,}/"#,
    r#"/(?:(?=g)).{2147483648,}/"#,
    r#"/(X(?:.(?!X))*?Y)|(Y(?:.(?!Y))*?Z)/g"#,
    r#"/[]/"#,
    r#"/ /"#,
    r#"/^\\uffff/"#,
    r#"/[&@!)OZ%3,#]/"#,
    r#"/\\\\\\n/g"#,
    r#"/foo.*baz/"#,
    r#"/[a-z]/g"#,
    r#"/()/"#,
    r#"/a|b/g"#,
    r#"/x|a|b/g"#,
    r#"/(?:a?)*/"#,
    r#"/:/"#,
    r#"/f/"#,
    r#"/c/"#,
    r#"/\\*/"#,
    r#"/n/"#,
    r#"/\\)/"#,
    r#"/\\\\/"#,
    r#"/((x)??){2}y/"#,
    r#"/((\\u66d6)??){7}J/"#,
    r#"/(a)/"#,
    r#"/(pattern)/g"#,
    r#"/foo/"#,
    r#"/.*star.*/i"#,
    r#"/can\'t open/"#,
    r#"/test.*[\\/\\\\]basic[\\/\\\\]/"#,
    r#"/(.)?@.*\\n/"#,
    r#"/1/g"#,
    r#"/uDC38/ug"#,
    r#"/b/"#,
    r#"/regexp/"#,
    r#"/()()()()/"#,
    r#"/(?:(?:(\")(c)\")?)*/"#,
    r#"/(?:(?:a*?(\")(c)\")?)*/"#,
    r#"/<script\\s*(?![^>]*type=[\'\"]?(?:dojo\\/|text\\/html\\b))(?:[^>]*?(?:src=([\'\"]?)([^>]*?)\\1[^>]*)?)*>([\\s\\S]*?)<\\/script>/gi"#,
    r#"/A|B/y"#,
    r#"/(x)y(z)/g"#,
    r#"/a(b)cd/g"#,
    r#"/(a)b(c)/g"#,
    r#"/(a)b(.)/g"#,
    r#"/(g)/g"#,
    r#"/^(?:\\s*.){0,16}/"#,
    r#"/is not a constructor/"#,
    r#"/^@(A*)x(B)*/"#,
    r#"/\\n/"#,
    r#"/[a-z]+/"#,
    r#"/(?:)/"#,
    r#"/((a|)+b)+/"#,
    r#"/.*b(cd)/"#,
    r#"/bcd.*/"#,
    r#"/.*bcd.*/"#,
    r#"/out-of-range index/"#,
    r#"/self-hosted/"#,
    r#"/^.@/"#,
    r#"/@.*$/g"#,
    r#"/@.*$/"#,
    r#"/(\\d+):\\d+$/"#,
    r#"/@/g"#,
    r#"/\\s/g"#,
    r#"/const.*for/"#,
    r#"/for.*const/"#,
    r#"/for.*in.*uneval/"#,
    r#"/for.*for.*for/"#,
    r#"/for.*for.*gc/"#,
    r#"/\\/.*[\\u0000\\u0080-\\uffff]/"#,
    r#"/abc/g"#,
    r#"/value that doesn\'t coerce purely/"#,
    r#"/ \\([^\\)]*\\)/g"#,
    r#"/fast exit trampoline to native/g"#,
    r#"/^call to( asm.js)? native .*\\(in wasm\\)$/g"#,
    r#"/(fast|slow) entry trampoline/g"#,
    r#"/(\\/[^\\/,<]+)*\\/testProfiling.js/g"#,
    r#"/testBuiltinD2D/g"#,
    r#"/assertThrowsInstanceOf/g"#,
    r#"/^ffi[12]?/g"#,
    r#"/,+/g"#,
    r#"/^,/"#,
    r#"/,$/"#,
    r#"/xyz/"#,
    r#"/\\u00ee[]/"#,
    r#"/[]/g"#,
    r#"/(de cuyo nombre no quiero acordarme)/"#,
    r#"/(Ἑλικωνιάδων ἀρχώμεθ᾽)/"#,
    r#"/disallowed/"#,
    r#"/foopy/"#,
    r#"/^\\[object (.*)\\]$/"#,
    r#"/can\'t start debugging: a debuggee script is on the stack/"#,
    r#"/^ds*$/"#,
    r#"/^s+Es+Es*$/"#,
    r#"/\\/\\*[BS]\\*\\//g"#,
    r#"/(\\r?\\n|\\r|\\u2028|\\u2029)/g"#,
    r#"/re/"#,
    r#"/Source-url-01.js line [0-9]+ > eval/"#,
    r#"/woops/"#,
    r#"/[sy]$/"#,
    r#"/Source-url-02.js .* > Function/"#,
    r#"/LL/"#,
    r#"/^wasm:(?:[^:]*:)*?[0-9a-f]{16}$/"#,
    r#"/[^B]/g"#,
    r#"/BB/"#,
    r#"/VAL/g"#,
    r#"/.*/"#,
    r#"/debugger/"#,
];
